FROM maven:3.9-eclipse-temurin-17  
WORKDIR /app  

RUN apt-get update && apt-get install -y git curl  

COPY . .  

RUN mvn dependency:go-offline  

EXPOSE 8080  

CMD ["sh", "-c", "mvn spring-boot:run && tail -f /dev/null"]